---
layout: page.academic
title: Lofivibe
permalink: /projects/lofivibe.html
---

## Lofivibe

Associated with Veermata Jijabai Technological Institute (VJTI)

A platform where users can listen to high-quality lofi music generated by deep learning models.

### Links

- <a href="https://github.com/ParamThakkar123/LofiMusicGenerator">GitHub Repository</a>

Skills: Tailwind CSS, TypeScript, Generative Models
